NavbarSettings: Instead of hiding the toggle, remove the pref from the main settings. The navbar preference screen is not intended for devices with hw buttons as these are not configured to use a soft navbar by default. Otherwise there is a FC because the dependency is missing in the XML.
java.lang.IllegalStateException: Dependency "enable_nav_bar" not found for preference "gesture_system_navigation" (title: "System navigation"
stacktrace: java.lang.IllegalStateException: Dependency "enable_nav_bar" not found for preference "gesture_system_navigation"

Signed-off-by: spezi77 <spezi7713@gmx.net>